// <auto-generated />
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]

[assembly: Guid("d8f1273a-7146-49d2-a093-12d95a9d2261")]
