//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnuCashIntegration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string Guid { get; set; }
        public string Name { get; set; }
        public string AccountType { get; set; }
        public string commodity_guid { get; set; }
        public long commodity_scu { get; set; }
        public long non_std_scu { get; set; }
        public string parent_guid { get; set; }
        public string code { get; set; }
        public string description { get; set; }
        public Nullable<long> hidden { get; set; }
        public Nullable<long> placeholder { get; set; }
    }
}
