//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnuCashIntegration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class billterms
    {
        public string guid { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public long refcount { get; set; }
        public long invisible { get; set; }
        public string parent { get; set; }
        public string child { get; set; }
        public string type { get; set; }
        public Nullable<long> duedays { get; set; }
        public Nullable<long> discountdays { get; set; }
        public Nullable<long> discount_num { get; set; }
        public Nullable<long> discount_denom { get; set; }
        public Nullable<long> cutoff { get; set; }
    }
}
