//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnuCashIntegration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetAmount
    {
        public long Id { get; set; }
        public string BudgetGuid { get; set; }
        public string AccountGuid { get; set; }
        public long PeriodNum { get; set; }
        public long AmountNumerator { get; set; }
        public long AmountDenominator { get; set; }
    }
}
