//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnuCashIntegration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commodity
    {
        public string guid { get; set; }
        public string @namespace { get; set; }
        public string mnemonic { get; set; }
        public string fullname { get; set; }
        public string cusip { get; set; }
        public long fraction { get; set; }
        public long quote_flag { get; set; }
        public string quote_source { get; set; }
        public string quote_tz { get; set; }
    }
}
