//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnuCashIntegration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees
    {
        public string guid { get; set; }
        public string username { get; set; }
        public string id { get; set; }
        public string language { get; set; }
        public string acl { get; set; }
        public long active { get; set; }
        public string currency { get; set; }
        public string ccard_guid { get; set; }
        public long workday_num { get; set; }
        public long workday_denom { get; set; }
        public long rate_num { get; set; }
        public long rate_denom { get; set; }
        public string addr_name { get; set; }
        public string addr_addr1 { get; set; }
        public string addr_addr2 { get; set; }
        public string addr_addr3 { get; set; }
        public string addr_addr4 { get; set; }
        public string addr_phone { get; set; }
        public string addr_fax { get; set; }
        public string addr_email { get; set; }
    }
}
