//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnuCashIntegration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class entries
    {
        public string guid { get; set; }
        public string date { get; set; }
        public string entered { get; set; }
        public string description { get; set; }
        public string action { get; set; }
        public string notes { get; set; }
        public Nullable<long> quantity_num { get; set; }
        public Nullable<long> quantity_denom { get; set; }
        public string i_acct { get; set; }
        public Nullable<long> i_price_num { get; set; }
        public Nullable<long> i_price_denom { get; set; }
        public Nullable<long> i_discount_num { get; set; }
        public Nullable<long> i_discount_denom { get; set; }
        public string invoice { get; set; }
        public string i_disc_type { get; set; }
        public string i_disc_how { get; set; }
        public Nullable<long> i_taxable { get; set; }
        public Nullable<long> i_taxincluded { get; set; }
        public string i_taxtable { get; set; }
        public string b_acct { get; set; }
        public Nullable<long> b_price_num { get; set; }
        public Nullable<long> b_price_denom { get; set; }
        public string bill { get; set; }
        public Nullable<long> b_taxable { get; set; }
        public Nullable<long> b_taxincluded { get; set; }
        public string b_taxtable { get; set; }
        public Nullable<long> b_paytype { get; set; }
        public Nullable<long> billable { get; set; }
        public Nullable<long> billto_type { get; set; }
        public string billto_guid { get; set; }
        public string order_guid { get; set; }
    }
}
