//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnuCashIntegration.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GnuCashDatabase : DbContext
    {
        public GnuCashDatabase()
            : base("name=GnuCashDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<billterms> billterms { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<BudgetAmount> BudgetAmounts { get; set; }
        public virtual DbSet<Budget> Budgets { get; set; }
        public virtual DbSet<Commodity> Commodities { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<employees> employees { get; set; }
        public virtual DbSet<entries> entries { get; set; }
        public virtual DbSet<invoices> invoices { get; set; }
        public virtual DbSet<jobs> jobs { get; set; }
        public virtual DbSet<lots> lots { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<prices> prices { get; set; }
        public virtual DbSet<Recurrence> Recurrences { get; set; }
        public virtual DbSet<ScheduledTransaction> ScheduledTransactions { get; set; }
        public virtual DbSet<Slot> Slots { get; set; }
        public virtual DbSet<Split> Splits { get; set; }
        public virtual DbSet<taxtable_entries> taxtable_entries { get; set; }
        public virtual DbSet<taxtables> taxtables { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<vendors> vendors { get; set; }
        public virtual DbSet<versions> versions { get; set; }
    }
}
