//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnuCashIntegration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoices
    {
        public string guid { get; set; }
        public string id { get; set; }
        public string date_opened { get; set; }
        public string date_posted { get; set; }
        public string notes { get; set; }
        public long active { get; set; }
        public string currency { get; set; }
        public Nullable<long> owner_type { get; set; }
        public string owner_guid { get; set; }
        public string terms { get; set; }
        public string billing_id { get; set; }
        public string post_txn { get; set; }
        public string post_lot { get; set; }
        public string post_acc { get; set; }
        public Nullable<long> billto_type { get; set; }
        public string billto_guid { get; set; }
        public Nullable<long> charge_amt_num { get; set; }
        public Nullable<long> charge_amt_denom { get; set; }
    }
}
