//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnuCashIntegration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public string guid { get; set; }
        public string id { get; set; }
        public string notes { get; set; }
        public string reference { get; set; }
        public long active { get; set; }
        public string date_opened { get; set; }
        public string date_closed { get; set; }
        public long owner_type { get; set; }
        public string owner_guid { get; set; }
    }
}
