//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnuCashIntegration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class prices
    {
        public string guid { get; set; }
        public string commodity_guid { get; set; }
        public string currency_guid { get; set; }
        public string date { get; set; }
        public string source { get; set; }
        public string type { get; set; }
        public long value_num { get; set; }
        public long value_denom { get; set; }
    }
}
