//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnuCashIntegration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recurrence
    {
        public long Id { get; set; }
        public string ScheduledTransactionGuid { get; set; }
        public long Multiplier { get; set; }
        public string PeriodType { get; set; }
        public string PeriodStart { get; set; }
    }
}
