//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnuCashIntegration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slot
    {
        public long Id { get; set; }
        public string ObjGuid { get; set; }
        public string Name { get; set; }
        public long SlotType { get; set; }
        public Nullable<long> Int64Val { get; set; }
        public string StringVal { get; set; }
        public Nullable<double> DoubleVal { get; set; }
        public string TimespecVal { get; set; }
        public string GuidVal { get; set; }
        public Nullable<long> NumericValNumerator { get; set; }
        public Nullable<long> NumericValDenominator { get; set; }
    }
}
