//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnuCashIntegration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Split
    {
        public string Guid { get; set; }
        public string TransactionGuid { get; set; }
        public string AccountGuid { get; set; }
        public string Memo { get; set; }
        public string Action { get; set; }
        public string ReconcileState { get; set; }
        public string ReconcileDate { get; set; }
        public long ValueNumerator { get; set; }
        public long ValueDenomerator { get; set; }
        public long QuantityNumerator { get; set; }
        public long QuantityDenominator { get; set; }
        public string LotGuid { get; set; }
    }
}
