//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnuCashIntegration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxtables
    {
        public string guid { get; set; }
        public string name { get; set; }
        public long refcount { get; set; }
        public long invisible { get; set; }
        public string parent { get; set; }
    }
}
