//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnuCashIntegration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class taxtable_entries
    {
        public long id { get; set; }
        public string taxtable { get; set; }
        public string account { get; set; }
        public long amount_num { get; set; }
        public long amount_denom { get; set; }
        public long type { get; set; }
    }
}
