//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GnuCashIntegration.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendors
    {
        public string guid { get; set; }
        public string name { get; set; }
        public string id { get; set; }
        public string notes { get; set; }
        public string currency { get; set; }
        public long active { get; set; }
        public long tax_override { get; set; }
        public string addr_name { get; set; }
        public string addr_addr1 { get; set; }
        public string addr_addr2 { get; set; }
        public string addr_addr3 { get; set; }
        public string addr_addr4 { get; set; }
        public string addr_phone { get; set; }
        public string addr_fax { get; set; }
        public string addr_email { get; set; }
        public string terms { get; set; }
        public string tax_inc { get; set; }
        public string tax_table { get; set; }
    }
}
