// <auto-generated />
using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]

[assembly: Guid("a41047cd-46fa-4a09-ac24-b443967fe1d1")]
