//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpBooks.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpBooks.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount and the transaction amount of a split must have the same value, if they are of the same security..
        /// </summary>
        internal static string AMOUNT_AND_TRANSACTION_AMOUNT_MUST_BE_EQUAL {
            get {
                return ResourceManager.GetString("AMOUNT_AND_TRANSACTION_AMOUNT_MUST_BE_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount and the transaction amount of a split must have the same sign..
        /// </summary>
        internal static string AMOUNT_AND_TRANSACTION_MUST_HAVE_SAME_SIGN {
            get {
                return ResourceManager.GetString("AMOUNT_AND_TRANSACTION_MUST_HAVE_SAME_SIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of a split must be evenly divisible by its account&apos;s smallest fraction..
        /// </summary>
        internal static string AMOUNT_OF_SPLIT_MUST_BE_DIVISIBLE {
            get {
                return ResourceManager.GetString("AMOUNT_OF_SPLIT_MUST_BE_DIVISIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The split must be assigned to an account..
        /// </summary>
        internal static string SPLIT_MUST_BE_ASSIGNED {
            get {
                return ResourceManager.GetString("SPLIT_MUST_BE_ASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction must have at least one split..
        /// </summary>
        internal static string TRANSACTION_MUST_HAVE_SPLIT {
            get {
                return ResourceManager.GetString("TRANSACTION_MUST_HAVE_SPLIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction must share the same security as at least one of its splits..
        /// </summary>
        internal static string TRANSACTION_MUST_SHARE_SECURITY_WITH_A_SPLIT {
            get {
                return ResourceManager.GetString("TRANSACTION_MUST_SHARE_SECURITY_WITH_A_SPLIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of the splits in the transaction must be equal to zero..
        /// </summary>
        internal static string TRANSACTION_SUM_MUST_BE_ZERO {
            get {
                return ResourceManager.GetString("TRANSACTION_SUM_MUST_BE_ZERO", resourceCulture);
            }
        }
    }
}
