//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpBooks.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpBooks.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the account to the book, because the account already belongs to the book..
        /// </summary>
        internal static string ACCOUNT_ALREADY_IN_BOOK {
            get {
                return ResourceManager.GetString("ACCOUNT_ALREADY_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account&apos;s smallest fraction must represent a whole number multiple of the units used by its security..
        /// </summary>
        internal static string ACCOUNT_FRACTION_MUST_BE_CONGRUENT_TO_SECURITY {
            get {
                return ResourceManager.GetString("ACCOUNT_FRACTION_MUST_BE_CONGRUENT_TO_SECURITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the account to the book, because another account has already been added with the same ID..
        /// </summary>
        internal static string ACCOUNT_ID_ALREADY_IN_BOOK {
            get {
                return ResourceManager.GetString("ACCOUNT_ID_ALREADY_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account may not share its ID with any of its ancestors..
        /// </summary>
        internal static string ACCOUNT_ID_MUST_BE_UNIQUE {
            get {
                return ResourceManager.GetString("ACCOUNT_ID_MUST_BE_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the account from the book, because the account currently has children..
        /// </summary>
        internal static string ACCOUNT_IN_USE_BY_CHILDREN {
            get {
                return ResourceManager.GetString("ACCOUNT_IN_USE_BY_CHILDREN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the account from the book, because the account currently has splits..
        /// </summary>
        internal static string ACCOUNT_IN_USE_BY_SPLITS {
            get {
                return ResourceManager.GetString("ACCOUNT_IN_USE_BY_SPLITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the account from the book, because the account is not a member of the book..
        /// </summary>
        internal static string ACCOUNT_NOT_FOUND_IN_BOOK {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_FOUND_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the account to the book, because the account&apos;s parent has not been added..
        /// </summary>
        internal static string ACCOUNT_PARENT_NOT_IN_BOOK {
            get {
                return ResourceManager.GetString("ACCOUNT_PARENT_NOT_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the account to the book, because another account has already been added with the same Name and Parent..
        /// </summary>
        internal static string ACCOUNT_REDUNDANT_BY_NAME_AND_PARENT {
            get {
                return ResourceManager.GetString("ACCOUNT_REDUNDANT_BY_NAME_AND_PARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the account to the book, because the account&apos;s security has not been added..
        /// </summary>
        internal static string ACCOUNT_SECURITY_NOT_IN_BOOK {
            get {
                return ResourceManager.GetString("ACCOUNT_SECURITY_NOT_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account specified is not a member of the book..
        /// </summary>
        internal static string ACCOUNT_SPECIFIED_NOT_IN_BOOK {
            get {
                return ResourceManager.GetString("ACCOUNT_SPECIFIED_NOT_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount and the transaction amount of a split must have the same value, if they are of the same security..
        /// </summary>
        internal static string AMOUNT_AND_TRANSACTION_AMOUNT_MUST_BE_EQUAL {
            get {
                return ResourceManager.GetString("AMOUNT_AND_TRANSACTION_AMOUNT_MUST_BE_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount and the transaction amount of a split must have the same sign..
        /// </summary>
        internal static string AMOUNT_AND_TRANSACTION_MUST_HAVE_SAME_SIGN {
            get {
                return ResourceManager.GetString("AMOUNT_AND_TRANSACTION_MUST_HAVE_SAME_SIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of a split must be evenly divisible by its account&apos;s smallest fraction..
        /// </summary>
        internal static string AMOUNT_OF_SPLIT_MUST_BE_DIVISIBLE {
            get {
                return ResourceManager.GetString("AMOUNT_OF_SPLIT_MUST_BE_DIVISIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the price quote to the book, because the price quote already belongs to the book..
        /// </summary>
        internal static string PRICE_QUOTE_ALREADY_IN_BOOK {
            get {
                return ResourceManager.GetString("PRICE_QUOTE_ALREADY_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the price quote to the book, because the price quote&apos;s currency has not been added..
        /// </summary>
        internal static string PRICE_QUOTE_CURRENCY_NOT_IN_BOOK {
            get {
                return ResourceManager.GetString("PRICE_QUOTE_CURRENCY_NOT_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the price quote to the book, because another price quote has already been added with the same ID..
        /// </summary>
        internal static string PRICE_QUOTE_ID_ALREADY_IN_BOOK {
            get {
                return ResourceManager.GetString("PRICE_QUOTE_ID_ALREADY_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the price quote from the book, because the price quote is not a member of the book..
        /// </summary>
        internal static string PRICE_QUOTE_NOT_IN_BOOK {
            get {
                return ResourceManager.GetString("PRICE_QUOTE_NOT_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the price quote to the book, because another price quote has already been added with the same Security, Currency, Date, and Source..
        /// </summary>
        internal static string PRICE_QUOTE_REDUNDANT_BY_SOURCE {
            get {
                return ResourceManager.GetString("PRICE_QUOTE_REDUNDANT_BY_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the price quote to the book, because the price quote&apos;s security has not been added..
        /// </summary>
        internal static string PRICE_QUOTE_SECURITY_NOT_IN_BOOK {
            get {
                return ResourceManager.GetString("PRICE_QUOTE_SECURITY_NOT_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could replay the book&apos;s modifications, because the save point could not be found..
        /// </summary>
        internal static string SAVE_POINT_NOT_FOUND {
            get {
                return ResourceManager.GetString("SAVE_POINT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Could not remove the save point, because it does not exist in the book..
        /// </summary>
        internal static string SAVE_POINT_NOT_IN_BOOK {
            get {
                return ResourceManager.GetString("SAVE_POINT_NOT_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the security to the book, because the security already belongs to the book..
        /// </summary>
        internal static string SECURITY_ALREADY_IN_BOOK {
            get {
                return ResourceManager.GetString("SECURITY_ALREADY_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fraction traded must be greater than or equal to one..
        /// </summary>
        internal static string SECURITY_FRACTION_TRADED_MUST_BE_POSITIVE {
            get {
                return ResourceManager.GetString("SECURITY_FRACTION_TRADED_MUST_BE_POSITIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the security to the book, because another security has already been added with the same ID..
        /// </summary>
        internal static string SECURITY_ID_ALREADY_IN_BOOK {
            get {
                return ResourceManager.GetString("SECURITY_ID_ALREADY_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the security from the book, because at least one account depends on it..
        /// </summary>
        internal static string SECURITY_IN_USE_BY_ACCOUNT {
            get {
                return ResourceManager.GetString("SECURITY_IN_USE_BY_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the security from the book, because at least one price quote depends on it..
        /// </summary>
        internal static string SECURITY_IN_USE_BY_PRICE_QUOTE {
            get {
                return ResourceManager.GetString("SECURITY_IN_USE_BY_PRICE_QUOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the security from the book, because at least one transaction depends on it..
        /// </summary>
        internal static string SECURITY_IN_USE_BY_TRANSACTION {
            get {
                return ResourceManager.GetString("SECURITY_IN_USE_BY_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the security from the book, because the security is not a member of the book..
        /// </summary>
        internal static string SECURITY_NOT_IN_BOOK {
            get {
                return ResourceManager.GetString("SECURITY_NOT_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the security to the book, because another security has already been added with the same Security Type and Symbol..
        /// </summary>
        internal static string SECURITY_REDUNDANT_BY_TYPE_AND_SYMBOL {
            get {
                return ResourceManager.GetString("SECURITY_REDUNDANT_BY_TYPE_AND_SYMBOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The split must not be assigned to an account that is identified as a grouping account..
        /// </summary>
        internal static string SPLIT_CANNOT_BE_ASSIGNED_TO_GROUPING_ACCOUNT {
            get {
                return ResourceManager.GetString("SPLIT_CANNOT_BE_ASSIGNED_TO_GROUPING_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The split must be assigned to an account..
        /// </summary>
        internal static string SPLIT_MUST_BE_ASSIGNED {
            get {
                return ResourceManager.GetString("SPLIT_MUST_BE_ASSIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The split must have a security..
        /// </summary>
        internal static string SPLIT_MUST_HAVE_A_SECURITY {
            get {
                return ResourceManager.GetString("SPLIT_MUST_HAVE_A_SECURITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security of a split must match the security of its account, if the account has a security specified..
        /// </summary>
        internal static string SPLIT_SECURITY_MUST_MATCH_ACCOUNT {
            get {
                return ResourceManager.GetString("SPLIT_SECURITY_MUST_MATCH_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the transaction to the book, because the transaction already belongs to the book..
        /// </summary>
        internal static string TRANSACTION_ALREADY_IN_BOOK {
            get {
                return ResourceManager.GetString("TRANSACTION_ALREADY_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the transaction to the book, because another transaction has already been added with the same Transaction Id..
        /// </summary>
        internal static string TRANSACTION_ID_ALREADY_IN_BOOK {
            get {
                return ResourceManager.GetString("TRANSACTION_ID_ALREADY_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction must have at least one split..
        /// </summary>
        internal static string TRANSACTION_MUST_HAVE_SPLIT {
            get {
                return ResourceManager.GetString("TRANSACTION_MUST_HAVE_SPLIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction must share the same security as at least one of its splits..
        /// </summary>
        internal static string TRANSACTION_MUST_SHARE_SECURITY_WITH_A_SPLIT {
            get {
                return ResourceManager.GetString("TRANSACTION_MUST_SHARE_SECURITY_WITH_A_SPLIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the transaction from the book, because the transaction is not a member of the book..
        /// </summary>
        internal static string TRANSACTION_NOT_IN_BOOK {
            get {
                return ResourceManager.GetString("TRANSACTION_NOT_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the transaction to the book, because the transaction is not valid..
        /// </summary>
        internal static string TRANSACTION_NOT_VALID {
            get {
                return ResourceManager.GetString("TRANSACTION_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the transaction to the book, because the transaction contains at least one split whose security has not been added..
        /// </summary>
        internal static string TRANSACTION_SPIT_SECURITY_NOT_IN_BOOK {
            get {
                return ResourceManager.GetString("TRANSACTION_SPIT_SECURITY_NOT_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the transaction to the book, because the transaction contains at least one split whose account has not been added..
        /// </summary>
        internal static string TRANSACTION_SPLIT_ACCOUNT_NOT_IN_BOOK {
            get {
                return ResourceManager.GetString("TRANSACTION_SPLIT_ACCOUNT_NOT_IN_BOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sum of the splits in the transaction must be equal to zero..
        /// </summary>
        internal static string TRANSACTION_SUM_MUST_BE_ZERO {
            get {
                return ResourceManager.GetString("TRANSACTION_SUM_MUST_BE_ZERO", resourceCulture);
            }
        }
    }
}
